# Generated by Django 3.1.3 on 2021-02-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20210224_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='name',
            new_name='bus',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bus',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='nr_plader',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Udvendig', 'Udvendig'), ('Udvendig + tank', 'Udvendig + tank'), ('Indvendig + Støvsuges', 'Indvendig + Støvsuges'), ('Indvendig + Støvsuges + Vinduer', 'Indvendig + Støvsuges + Vinduer')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='todo_list.Tag'),
        ),
    ]
