# Generated by Django 3.1.3 on 2021-02-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_auto_20210224_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Ikke_klar', 'Ikke_klar'), ('Klar', 'Klar')], max_length=200, null=True),
        ),
    ]
