# Generated by Django 3.1.3 on 2021-03-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_auto_20210305_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vinduer',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
    ]
